"use client";

import { useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import logo from "../public/icons/upload.png";
import Header from "./components/header";

export default function Home() {
  const router = useRouter();

  // 状态
  const [jobDescription, setJobDescription] = useState("");
  const [selectedFile, setSelectedFile] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [formError, setFormError] = useState("");

  // file input
  const fileInputRef = useRef(null);

  const fileName = useMemo(() => {
    if (!selectedFile) return "";
    return selectedFile.name;
  }, [selectedFile]);

  // 点击 Browse Files
  const handleBrowseClick = () => {
    setFormError("");

    // 每次重新选择，避免误用旧文件
    setSelectedFile(null);

    // 清空 input value，允许重复选择同一个文件也触发 onChange
    if (fileInputRef.current) fileInputRef.current.value = "";

    fileInputRef.current?.click();
  };

  // 选文件
  const handleFileChange = (e) => {
    setFormError("");
    const file = e.target.files?.[0];
    if (!file) return;

    // 只允许 PDF
    if (file.type !== "application/pdf") {
      setSelectedFile(null);
      setFormError("Please upload a PDF file.");
      return;
    }

    // 限制大小 10MB
    const maxSizeMB = 10;
    if (file.size > maxSizeMB * 1024 * 1024) {
      setSelectedFile(null);
      setFormError(`File is too large. Please upload a PDF under ${maxSizeMB}MB.`);
      return;
    }

    setSelectedFile(file);
  };

  // Analyze
  const handleAnalyze = async () => {
    setFormError("");

    // 前端校验
    if (!selectedFile) {
      setFormError("Please upload your resume PDF before analyzing.");
      return;
    }
    if (!jobDescription.trim()) {
      setFormError("Please paste the job description before analyzing.");
      return;
    }

    setIsLoading(true);

    try {
      // 真实上传链路 - FormData
      const formData = new FormData();
      formData.append("resume", selectedFile);
      formData.append("jobDescription", jobDescription);
      // formData.append("simulate", "success");
      // formData.append("simulate", "fail");
      // formData.append("delayMs", "900");

      const res = await fetch("/api/analyze", {
        method: "POST",
        body: formData,
      });

      const data = await res.json().catch(() => null);

      // 失败：把错误信息存起来，跳 fails 页面
      if (!res.ok || !data || data.ok !== true) {
        const msg =
          data?.error?.message ||
          "We couldn't analyze your resume right now. Please try again.";

        sessionStorage.setItem("ai_error", msg);
        router.push("/fails-score");
        return;
      }

      // Phase 4 正确做法：把 report and meta 存到 sessionStorage，success 页读取
      sessionStorage.setItem("ai_resume_report", JSON.stringify(data.report));
      sessionStorage.setItem("ai_resume_meta", JSON.stringify(data.meta));

      //也保存 JD、文件名
      sessionStorage.setItem("ai_jd", jobDescription);
      sessionStorage.setItem("ai_fileName", fileName || "");

      // 成功跳转
      router.push("/success-score");
    } catch (err) {
      // 网络/未知错误
      sessionStorage.setItem(
        "ai_error",
        "Network error. Please check your connection and try again."
      );
      router.push("/fails-score");
    } finally {
      setIsLoading(false);
    }


  };

  return (
    <main className="min-h-screen bg-white">
      <div className="mx-auto max-w-5xl px-4 py-10">

        <h1 className="text-4xl font-bold flex items-center gap-3">
          AI Resume Analyzer
          <span className="text-xs px-2 py-1 rounded-full bg-indigo-50 text-indigo-600 border border-indigo-200">
            AI powered by Claude 3 Haiku (AWS Bedrock)
          </span>
        </h1>
        <p className="text-gray-400 mt-2 mb-6 text-sm">
          Get instant feedback on how well your resume matches the job you want.
        </p>


        <section className="relative rounded-2xl border border-gray-200 bg-white p-8 shadow-sm">
          {/* Loading overlay */}
          {isLoading && (
            <div className="absolute inset-0 z-20 flex items-center justify-center rounded-2xl bg-white/80 backdrop-blur-sm">
              <div className="rounded-2xl border border-gray-200 bg-white px-8 py-6 shadow-sm">
                <div className="flex items-center gap-3">
                  <div className="h-5 w-5 animate-spin rounded-full border-2 border-gray-300 border-t-gray-800" />
                  <p className="text-sm font-semibold text-gray-900">
                    Analyzing… Please wait
                  </p>
                </div>
                <p className="mt-2 text-xs text-gray-500">
                  Results are generated by the analysis API.
                </p>
              </div>
            </div>
          )}

          <p className="mb-4 text-gray-700">Upload your Resume/CV in PDF format</p>

          <div className="rounded-xl bg-gray-200 px-6 py-6">
            <div className="flex items-center justify-between gap-6">
              <div className="flex items-start gap-3">
                <Image src={logo} alt="upload logo" width={22} height={22} />

                <div className="space-y-1">
                  <h3 className="text-sm font-semibold text-gray-900">
                    Drag and Drop your file here
                  </h3>

                  <p className="text-xs text-gray-600">
                    {fileName ? (
                      <>
                        Selected:{" "}
                        <span className="font-medium text-gray-900">{fileName}</span>
                      </>
                    ) : (
                      "PDF only • Recommended under 10MB "
                    )}
                  </p>
                </div>
              </div>

              {/* Browse */}
              <button
                className="shrink-0 rounded-xl bg-indigo-800 px-5 py-2 text-sm font-semibold text-white hover:bg-indigo-600 disabled:opacity-60"
                type="button"
                onClick={handleBrowseClick}
                disabled={isLoading}
              >
                Browse Files
              </button>

              {/* Hidden input */}
              <input
                ref={fileInputRef}
                type="file"
                accept="application/pdf"
                onChange={handleFileChange}
                className="hidden"
              />
            </div>
          </div>

          {/* JD */}
          <div>
            <p className="mb-4 text-gray-700 mt-7">
              Enter the Job Description of the role you are applying for:
            </p>

            <div className="rounded-xl bg-gray-200 px-6 py-6">
              <textarea
                value={jobDescription}
                onChange={(e) => {
                  setJobDescription(e.target.value);
                  setFormError("");
                }}
                disabled={isLoading}
                placeholder="Job Description"
                className="
                  w-full
                  h-32
                  bg-transparent
                  text-sm
                  text-gray-700
                  placeholder-gray-500
                  outline-none
                  resize-none
                "
              />
            </div>
          </div>

          {/* Error */}
          {formError && (
            <div className="mt-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
              {formError}
            </div>
          )}

          {/* Analyze button */}
          <button
            type="button"
            onClick={handleAnalyze}
            disabled={isLoading}
            className="mt-8 rounded-2xl border border-indigo-700 px-5 py-2.5 font-semibold text-indigo-900 hover:bg-indigo-50 disabled:cursor-not-allowed disabled:opacity-60"
          >
            {isLoading ? "Analyzing..." : " Analyze Resume"}
          </button>
        </section>
      </div>
    </main>
  );
}
